### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karl-police**
Added version

Also are you on Discord? Maybe you could join Discord.gg/SourceEngine

### CODE REVIEW

**Comment by rihi** [comment]
This repository isn't actually used for active development on bspsrc. The additions in this repo are all additions I made in my own [repo](https://github.com/rihi/bspsrc) and the owner of this one merely merged them into his own one for personal use (Probably offline testing or whatever). You can't really see it in the github network view, because there was a force push to the offical bspsrc repository, which changed a lot of commit hashes and the owner of this repo didn't rebase/update his branch so far.

Also, all these changes were already merged into the official bspsrc [repository](https://github.com/ata4/bspsrc) recently. (Mainly with ata4/bspsrc#68, ata4/bspsrc#70, ata4/bspsrc#74, ata4/bspsrc#75, ata4/bspsrc#76)
And even though the owner of bspsrc doesn’t actively develop the software, he still manages the repository and will try to publish a new version if he has time for it.

If you need a compiled version now though, you could use my temporary [release](https://github.com/rihi/bspsrc/releases) which includes all recent changes.

**Comment by karl-police** [comment]
> This repository isn't actually used for active development on bspsrc. The additions in this repo are all additions I made in my own [repo](https://github.com/rihi/bspsrc) and the owner of this one merely merged them into his own one for personal use (Probably offline testing or whatever). You can't really see this in the github network view anymore, because there was a force push to the offical bspsrc repository, which changed a lot of commit hashes and the owner of this repo didn't rebase/update his branch so far.
> 
> Also, all these changes were already merged into the official bspsrc [repository](https://github.com/ata4/bspsrc) recently. (Mainly with [ata4#68](https://github.com/ata4/bspsrc/pull/68), [ata4#70](https://github.com/ata4/bspsrc/pull/70), [ata4#74](https://github.com/ata4/bspsrc/pull/74), [ata4#75](https://github.com/ata4/bspsrc/pull/75), [ata4#76](https://github.com/ata4/bspsrc/pull/76))
> And even though the owner of bspsrc doesn’t actively develop the software, he still manages the repository and will try to publish a new version if he has time for it.
> 
> If you need a compiled version now though, you could use my temporary [release](https://github.com/rihi/bspsrc/releases) which includes all recent changes.

oh well I've only been linked this one

**Comment by karl-police** [comment]
people complain now which one is not outdated

**Comment by karl-police** [comment]
also what's your discord?

**Comment by rihi** [comment]
> 
> 
> > This repository isn't actually used for active development on bspsrc. The additions in this repo are all additions I made in my own [repo](https://github.com/rihi/bspsrc) and the owner of this one merely merged them into his own one for personal use (Probably offline testing or whatever). You can't really see this in the github network view anymore, because there was a force push to the offical bspsrc repository, which changed a lot of commit hashes and the owner of this repo didn't rebase/update his branch so far.
> > Also, all these changes were already merged into the official bspsrc [repository](https://github.com/ata4/bspsrc) recently. (Mainly with [ata4#68](https://github.com/ata4/bspsrc/pull/68), [ata4#70](https://github.com/ata4/bspsrc/pull/70), [ata4#74](https://github.com/ata4/bspsrc/pull/74), [ata4#75](https://github.com/ata4/bspsrc/pull/75), [ata4#76](https://github.com/ata4/bspsrc/pull/76))
> > And even though the owner of bspsrc doesn’t actively develop the software, he still manages the repository and will try to publish a new version if he has time for it.
> > If you need a compiled version now though, you could use my temporary [release](https://github.com/rihi/bspsrc/releases) which includes all recent changes.
> 
> oh well I've only been linked this one also I compiled it myself but I didn't see the updates

Yeah, no problem. When I saw your pull request here, I guessed that someone linked you here.
Funnily enough, after some 'researching' I learned that apparently everybody thinks, KudCode (no offense to him, not really his fault) made all these changes instead of me? (Eg: tophattwaffle has this repo starred :sweat_smile:)

Like, you can even see, that his master branch just contains merges of my branches (Eg: c1cc19c6d8770b9d3c720a1d9c2747f0fd728051)

> 
> 
> also what's your discord?

Rihi#0123

**Pull request closed without merging**
